USE Subscription
GO

TRUNCATE TABLE Subscription.dbo.CompanyContacts;
DECLARE @Max int = 381;
DBCC CHECKIDENT (CompanyContacts, RESEED, @Max);

DISABLE TRIGGER ALL ON Subscription.dbo.CompanyContacts;

SET IDENTITY_INSERT Subscription.dbo.CompanyContacts ON

INSERT INTO 
	[dbo].[CompanyContacts]
    ([ID],[CompanyID],[ContactPrefix],[ContactFirstName],[ContactMiddleInitial],[ContactLastName],[ContactSuffix],[CompanyLocationID],
	[ContactEmailAddress],[ContactPhone],[ContactPhoneExtension],[ContactFax],[Designation],[Department],[Role],[Notes],
	[PrimaryContact],[CreatedBy],[CreatedDate],[UpdatedBy],[UpdatedDate])
SELECT
    A.CONTACT_ID,A.PARENT_ENTITY_ID,'',A.FIRST_NAME,ISNULL(A.MIDDLE_NAME, '') AS MIDDLE_NAME,A.LAST_NAME,'',0,B.ECOMM,dbo.StripNonNumeric(EP.PHONE) AS PHONE,'','',D.DESIGNATION,
    A.DEPARTMENT,3,ISNULL(E.NOTES, '') AS NOTES,CAST(CASE WHEN A.CONTACT_ID = (SELECT MIN(C2.CONTACT_ID) FROM TitanPSS.dbo.CONTACT C2 WHERE C2.PARENT_ENTITY_ID = A.PARENT_ENTITY_ID)
	THEN 1 ELSE 0 END AS BIT) AS [PRIMARY],A.CREATED_BY,A.DATE_CREATED,A.UPDATED_BY,A.DATE_UPDATED
FROM 
	TitanPSS.dbo.CONTACT A LEFT JOIN TitanPSS.dbo.ENTITY_ECOMM B ON A.CONTACT_ID = B.ENTITY_ID AND B.ENTITY_TYPE_CODE = 'CNT'
	OUTER APPLY (SELECT TOP 1 EP.PHONE FROM TitanPSS.dbo.ENTITY_PHONE EP WHERE EP.ENTITY_ID = A.CONTACT_ID AND EP.ENTITY_TYPE_CODE = 'CNT' 
		AND EP.PHONE_TYPE_CODE IN ('WKPH', 'CELL', 'HMPH', 'FAX', 'OTPH') ORDER BY CASE EP.PHONE_TYPE_CODE WHEN 'WKPH' THEN 1 WHEN 'CELL' THEN 2 WHEN 'HMPH' THEN 3 WHEN 'FAX' THEN 4
		WHEN 'OTPH' THEN 5 ELSE 6 END) EP
	INNER JOIN TitanPSS.dbo.DESIGNATION D ON A.DESIGNATION_ID = D.DESIGNATION_ID
	LEFT JOIN TitanPSS.dbo.ENTITY_NOTES E ON A.CONTACT_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CODE = 'CNT'
ORDER BY A.PARENT_ENTITY_ID;
GO

